
[general]
	#If false, automatically hide the 'rotten in X days' tooltip.
	enableTFCDecayDisplay = false
	#If true, food stack counts will render behind the weight bar
	enableFoodShowsStackCount = false
	#The value that should be displayed as the maximum ounces (or whatever kind of weight type you choose) a food item could weigh. By default, a full stack is 160 ounces.
	#Range: > 1
	maxOunces = 16
	#Enable rendering a food weight bar
	enableFoodWeightRender = true
	#Enable rendering a food weight bar
	enableFoodDecayRender = true
	#If true, SI units will be used for food weight instead of the traditional oz. The name of this config option is a joke, I know SI units are used outside of Europe.
	enableEuropeanMode = false

