
#Client settings
[client]
	#Should the hunger bar have a gilded overlay when the player has the Nourishment effect?
	nourishmentHungerOverlay = false
	#Should the health bar have a silver sheen when the player has the Comfort effect?
	comfortHealthOverlay = false
	#Should meal and drink tooltips display which effects they provide?
	foodEffectTooltip = true

